foreground              #FFFFFF
background              #242120
selection_foreground    #242120
selection_background    #FFFFFF
cursor                  #F1F3F1
cursor_text_color       #020202

active_tab_foreground     #242120
active_tab_background     #B2A6AA
inactive_tab_foreground   #B2A6AA
inactive_tab_background   #242120

# black
color0      #523329
color8      #8F6557

# red
color1      #CCFFCC
color9      #AAF0AA

# green
color2      #FFDBCC
color10     #F0BFAA

# yellow
color3      #FFCCDD
color11     #F0AAC1

# blue
color4      #E6AD9A
color12     #E6AD9A

# magenta
color5      #E6B09A
color13     #E6B09A

# cyan
color6      #E69AB3
color14     #E69AB3

# white
color7      #CCFFCC
color15     #AAF0AA
