$HYDE_HYPRLAND=set #! Do not remove - HyDE marker to prevent file overwrite

#* You can freely edit this file, but make sure to not remove the above line!
#* All Files Below are yours to modify!

#!     ░▒▒▒░░░▓▓         ___________
#!    ░░▒▒▒░░░░░▓▓       //___________/
#!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#!   ░░▒▒░░░░▓▓▓▓▓ | | | | |  | |  __/
#!    ░▒▒░░░▓▓   ▓▓ | |_| | |_/ /| |___
#!     ░▒▒░░▓▓   ▓▓  \__  |____/ |____/
#!      ░▒▓▓   ▓▓  //____/

source = $HOME/.local/share/hyde/hyprland.conf # Fallback when HYPRLAND_CONFIG is not set

source = ./windowrules.conf # Window rules
source = ./monitors.conf # Monitor configuration
source = ./userprefs.conf # Your hyprland configuration
source = ./keybindings.conf # Keyboard shortcuts (now loaded once)

exec-once = libinput-gestures-setup start

# Abix layer - custom config
source = $XDG_CONFIG_HOME/abix/abix.conf