#!/usr/bin/env bash
# abix-wall.sh - Set wallpaper with optional color generation
# Part of AbixOS - HyDE-inspired but independent

set -euo pipefail

# Configuration
WALLPAPER_DIR="${HOME}/Pictures/wallpapers"
CACHE_DIR="${HOME}/.cache/abix/wallpaper"
COLOR_CACHE="${HOME}/.cache/abix/wallbash"
SCRIPTS_DIR="${HOME}/.config/abix/scripts"

# Create directories if they don't exist
mkdir -p "${WALLPAPER_DIR}" "${CACHE_DIR}" "${COLOR_CACHE}"

# Dependencies
DEPENDENCIES=(swww hyprctl notify-send)
for dep in "${DEPENDENCIES[@]}"; do
    if ! command -v "${dep}" &> /dev/null; then
        echo "Error: ${dep} is required but not installed." >&2
        exit 1
    fi
done

# Default wallpaper if none specified
DEFAULT_WALLPAPER="${WALLPAPER_DIR}/default.jpg"

# Help message
show_help() {
    cat << EOF
Usage: abix-wall.sh [OPTIONS] [wallpaper_path]

Options:
  -r, --random    Set a random wallpaper from WALLPAPER_DIR
  -c, --color     Generate color scheme from wallpaper (requires wallbash)
  -h, --help      Show this help message
  -v, --verbose   Verbose output

If no wallpaper_path is provided and neither -r nor -c is used,
a file picker will be launched using rofi (if available).

Examples:
  abix-wall.sh                           # Interactive selection
  abix-wall.sh -r                        # Random wallpaper
  abix-wall.sh ~/Pictures/wall.jpg       # Specific wallpaper
  abix-wall.sh -c ~/Pictures/wall.jpg    # With color generation
EOF
}

# Parse arguments
RANDOM=false
GENERATE_COLOR=false
VERBOSE=false
WALLPAPER=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -r|--random)
            RANDOM=true
            shift
            ;;
        -c|--color)
            GENERATE_COLOR=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        *)
            if [[ -z "$WALLPAPER" ]]; then
                WALLPAPER="$1"
            else
                echo "Error: Multiple wallpapers specified" >&2
                exit 1
            fi
            shift
            ;;
    esac
done

# Log function
log() {
    if [[ "$VERBOSE" == true ]]; then
        echo "[abix-wall] $1"
    fi
}

# Set wallpaper using swww
set_wallpaper() {
    local img_path="$1"
    
    if [[ ! -f "$img_path" ]]; then
        echo "Error: Wallpaper file not found: $img_path" >&2
        return 1
    fi
    
    log "Setting wallpaper: $img_path"
    
    # Use swww to set wallpaper with fade transition
    if swww query &> /dev/null; then
        swww img "$img_path" --transition-type fade --transition-duration 2.0
    else
        # Start swww daemon if not running
        swww init
        swww img "$img_path" --transition-type fade --transition-duration 2.0
    fi
    
    # Store current wallpaper path
    echo "$img_path" > "${CACHE_DIR}/current"
    
    # Notify user
    notify-send -a "AbixOS" "Wallpaper set" "$(basename "$img_path")" -i "$img_path" 2>/dev/null || true
    
    return 0
}

# Generate color scheme from wallpaper (simplified version)
generate_colors() {
    local img_path="$1"
    
    if [[ ! -f "$img_path" ]]; then
        echo "Error: Image file not found: $img_path" >&2
        return 1
    fi
    
    log "Generating color scheme from: $img_path"
    
    # Check if ImageMagick is available for color extraction
    if ! command -v convert &> /dev/null; then
        warn "ImageMagick not found. Skipping color generation."
        warn "Install imagemagick for color generation support."
        return 0
    fi
    
    # Create a simple color palette from the image
    # Extract dominant colors using ImageMagick
    local temp_palette="${CACHE_DIR}/palette.$$.png"
    local colors_file="${COLOR_CACHE}/current.colors"
    
    # Resize image for faster processing
    convert "$img_path" -resize 100x100\! -unique-colors -resize 10x1\! "$temp_palette"
    
    # Extract top 5 colors
    local colors
    colors=$(convert "$temp_palette" -format "%c" histogram:info:- | \
             sort -nr -k1 | \
             head -5 | \
             sed 's/.*: //g' | \
             tr '\n' ' ' | \
             sed 's/ $//')
    
    if [[ -n "$colors" ]]; then
        # Create a simple color definition file
        {
            echo "# Generated by abix-wall.sh"
            echo "# Source: $(basename "$img_path")"
            echo ""
            # Format as simple variables that can be sourced
            local i=1
            for color in $colors; do
                # Convert hex to decimal for rgba if needed
                echo "WALLPAPER_COLOR_${i}=${color}"
                ((i++))
            done
            echo ""
            echo "# Optional: Source this file to use colors:"
            echo "# source \"${COLOR_CACHE}/current.colors\""
        } > "$colors_file"
        
        log "Color scheme saved to: $colors_file"
        notify-send -a "AbixOS" "Colors generated" "Extracted $(echo $colors | wc -w) colors" 2>/dev/null || true
    else
        warn "Could not extract colors from image"
    fi
    
    # Cleanup
    rm -f "$temp_palette"
    
    return 0
}

# Main execution
main() {
    local selected_wallpaper="$DEFAULT_WALLPAPER"
    
    # Determine which wallpaper to use
    if [[ "$RANDOM" == true ]]; then
        # Select random wallpaper from directory
        if [[ -d "$WALLPAPER_DIR" ]]; then
            mapfile -t wallpapers < <(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) 2>/dev/null)
            if [[ ${#wallpapers[@]} -gt 0 ]]; then
                selected_wallpaper="${wallpapers[RANDOM % ${#wallpapers[@]}]}"
                log "Selected random wallpaper: $selected_wallpaper"
            else
                warn "No wallpapers found in $WALLPAPER_DIR"
                selected_wallpaper="$DEFAULT_WALLPAPER"
            fi
        else
            warn "Wallpaper directory not found: $WALLPAPER_DIR"
            # Create default wallpaper if none exists
            if [[ ! -f "$DEFAULT_WALLPAPER" ]]; then
                # Create a simple gradient as default
                convert -size 1920x1080 gradient:#1a1a2e:#16213e "$DEFAULT_WALLPAPER" 2>/dev/null || \
                echo "## Default wallpaper placeholder" > "$DEFAULT_WALLPAPER"
            fi
            selected_wallpaper="$DEFAULT_WALLPAPER"
        fi
    elif [[ -n "$WALLPAPER" ]]; then
        # Use specified wallpaper
        selected_wallpaper="$WALLPAPER"
    else
        # Interactive selection with rofi if available
        if command -v rofi &> /dev/null && [[ -d "$WALLPAPER_DIR" ]]; then
            mapfile -t wallpapers < <(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) 2>/dev/null | sort)
            
            if [[ ${#wallpapers[@]} -gt 0 ]]; then
                # Create temporary menu
                local menu_file
                menu_file=$(mktemp)
                for wp in "${wallpapers[@]}"; do
                    echo "$(basename "$wp")" >> "$menu_file"
                done
                
                local choice
                choice=$(rofi -dmenu -p "Select Wallpaper" < "$menu_file" || true)
                rm -f "$menu_file"
                
                if [[ -n "$choice" ]]; then
                    # Find full path
                    for wp in "${wallpapers[@]}"; do
                        if [[ "$(basename "$wp")" == "$choice" ]]; then
                            selected_wallpaper="$wp"
                            break
                        fi
                    done
                fi
            else
                warn "No wallpapers found in $WALLPAPER_DIR"
            fi
        else
            # Fallback to first available or default
            if [[ -d "$WALLPAPER_DIR" ]]; then
                mapfile -t wallpapers < <(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) 2>/dev/null | head -1)
                if [[ ${#wallpapers[@]} -gt 0 ]]; then
                    selected_wallpaper="${wallpapers[0]}"
                fi
            fi
        fi
    fi
    
    # Set the wallpaper
    if set_wallpaper "$selected_wallpaper"; then
        # Generate colors if requested
        if [[ "$GENERATE_COLOR" == true ]]; then
            generate_colors "$selected_wallpaper"
        fi
        
        success "Wallpaper set successfully"
        exit 0
    else
        error "Failed to set wallpaper"
        exit 1
    fi
}

# Helper functions for output
warn() {
    echo "[abix-wall] WARNING: $1" >&2
}

error() {
    echo "[abix-wall] ERROR: $1" >&2
}

success() {
    echo "[abix-wall] SUCCESS: $1"
}

# Execute main function
main "$@"